import { LucideIcon } from 'lucide-react';
import {
  // Existing
  FlaskConical,
  ClipboardCheck,
  SearchCode,
  FileText,
  Bug,
  CircleDot,
  ArrowLeft,
  Upload,
  Zap,
  Loader2,
  Check,
  Terminal,
  CheckCircle2,
  XCircle,
  Clock,
  Circle,
  Cpu,
  RefreshCw,
  ScrollText,
  Code,
  Download,
  Copy,
  FileCode,
  FileX,
  ArrowRight,
  Sparkles,
  X,
  Command,
  // Category icons
  ShieldCheck,
  Rocket,
  Target,
  Ticket,
  Database,
  Users,
  Headphones,
  // Agent icons - Code Quality
  FileCode2,
  Trash2,
  Shield,
  GitBranch,
  // Agent icons - Testing
  MonitorPlay,
  ListChecks,
  Table,
  PieChart,
  // Agent icons - Documentation
  MessageSquareCode,
  BookOpen,
  History,
  Lightbulb,
  ClipboardList,
  // Agent icons - Dev Productivity
  Package,
  FileJson,
  Settings,
  Wand2,
  // Agent icons - DevOps
  CheckSquare,
  GitCompare,
  Workflow,
  Undo2,
  AlertTriangle,
  // Agent icons - Requirements
  FileSearch,
  Link,
  // Agent icons - Event Management
  Network,
  ArrowRightLeft,
  ArrowUp,
  // Agent icons - SYSPRO Specific
  Compass,
  FormInput,
  ArrowUpCircle,
  // Agent icons - Team & Process
  BarChart,
  UserPlus,
  FileEdit,
  UserCheck,
  // Agent icons - Customer Support
  Mail,
  GraduationCap,
  HelpCircle,
  Presentation,
} from 'lucide-react';

// Map of icon names to their components
const iconMap: Record<string, LucideIcon> = {
  // Existing
  FlaskConical,
  ClipboardCheck,
  SearchCode,
  FileText,
  Bug,
  CircleDot,
  ArrowLeft,
  Upload,
  Zap,
  Loader2,
  Check,
  Terminal,
  CheckCircle2,
  XCircle,
  Clock,
  Circle,
  Cpu,
  RefreshCw,
  ScrollText,
  Code,
  Download,
  Copy,
  FileCode,
  FileX,
  ArrowRight,
  Sparkles,
  X,
  Command,
  // Category icons
  ShieldCheck,
  Rocket,
  Target,
  Ticket,
  Database,
  Users,
  Headphones,
  HeadphonesIcon: Headphones,
  // Agent icons - Code Quality
  FileCode2,
  Trash2,
  Shield,
  GitBranch,
  // Agent icons - Testing
  MonitorPlay,
  ListChecks,
  Table,
  PieChart,
  // Agent icons - Documentation
  MessageSquareCode,
  BookOpen,
  History,
  Lightbulb,
  ClipboardList,
  // Agent icons - Dev Productivity
  Package,
  FileJson,
  Settings,
  Wand2,
  // Agent icons - DevOps
  CheckSquare,
  GitCompare,
  Workflow,
  Undo2,
  AlertTriangle,
  // Agent icons - Requirements
  FileSearch,
  Link,
  // Agent icons - Event Management
  Network,
  ArrowRightLeft,
  ArrowUp,
  // Agent icons - SYSPRO Specific
  Compass,
  FormInput,
  ArrowUpCircle,
  // Agent icons - Team & Process
  BarChart,
  UserPlus,
  FileEdit,
  UserCheck,
  // Agent icons - Customer Support
  Mail,
  GraduationCap,
  HelpCircle,
  Presentation,
};

export function getIcon(name: string): LucideIcon {
  return iconMap[name] || CircleDot;
}

export {
  // Existing
  FlaskConical,
  ClipboardCheck,
  SearchCode,
  FileText,
  Bug,
  CircleDot,
  ArrowLeft,
  Upload,
  Zap,
  Loader2,
  Check,
  Terminal,
  CheckCircle2,
  XCircle,
  Clock,
  Circle,
  Cpu,
  RefreshCw,
  ScrollText,
  Code,
  Download,
  Copy,
  FileCode,
  FileX,
  ArrowRight,
  Sparkles,
  X,
  Command,
  // Category icons
  ShieldCheck,
  Rocket,
  Target,
  Ticket,
  Database,
  Users,
  Headphones,
  // Agent icons - Code Quality
  FileCode2,
  Trash2,
  Shield,
  GitBranch,
  // Agent icons - Testing
  MonitorPlay,
  ListChecks,
  Table,
  PieChart,
  // Agent icons - Documentation
  MessageSquareCode,
  BookOpen,
  History,
  Lightbulb,
  ClipboardList,
  // Agent icons - Dev Productivity
  Package,
  FileJson,
  Settings,
  Wand2,
  // Agent icons - DevOps
  CheckSquare,
  GitCompare,
  Workflow,
  Undo2,
  AlertTriangle,
  // Agent icons - Requirements
  FileSearch,
  Link,
  // Agent icons - Event Management
  Network,
  ArrowRightLeft,
  ArrowUp,
  // Agent icons - SYSPRO Specific
  Compass,
  FormInput,
  ArrowUpCircle,
  // Agent icons - Team & Process
  BarChart,
  UserPlus,
  FileEdit,
  UserCheck,
  // Agent icons - Customer Support
  Mail,
  GraduationCap,
  HelpCircle,
  Presentation,
};
