'use client';

import { useCallback } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { OrbitSystem } from '@/components/orb/OrbitSystem';
import { DynamicForm } from '@/components/form/DynamicForm';
import { ExecutionMonitor } from '@/components/execution/ExecutionMonitor';
import { ResultsViewer } from '@/components/results/ResultsViewer';
import { CommandInput } from '@/components/ui/CommandInput';
import { agents } from '@/config/agents';
import { useAppStore } from '@/store/app-store';
import { Agent, ExecutionRun, ExecutionStatus } from '@/types/agent';

export default function Home() {
  const {
    selectedAgent,
    setSelectedAgent,
    viewState,
    setViewState,
    currentExecution,
    setCurrentExecution,
    addExecution,
    updateExecution,
  } = useAppStore();

  const handleAgentSelect = useCallback(
    (agent: Agent) => {
      setSelectedAgent(agent);
      setViewState('form');
    },
    [setSelectedAgent, setViewState]
  );

  const handleBack = useCallback(() => {
    setSelectedAgent(null);
    setViewState('orbit');
    setCurrentExecution(null);
  }, [setSelectedAgent, setViewState, setCurrentExecution]);

  const handleFormSubmit = useCallback(
    async (data: Record<string, unknown>) => {
      if (!selectedAgent) return;

      // Create execution record
      const execution: ExecutionRun = {
        id: `exec-${Date.now()}`,
        agentId: selectedAgent.id,
        status: 'queued',
        inputs: data,
        startedAt: new Date(),
        progress: 0,
        statusMessage: 'Initializing agent...',
      };

      setCurrentExecution(execution);
      addExecution(execution);
      setViewState('executing');

      // Simulate execution progress (replace with real n8n webhook calls)
      const simulateProgress = async () => {
        const statuses: { status: ExecutionStatus; message: string; progress: number }[] = [
          { status: 'running', message: 'Connecting to n8n workflow...', progress: 10 },
          { status: 'running', message: 'Sending request to agent...', progress: 30 },
          { status: 'processing', message: 'Agent is analyzing inputs...', progress: 50 },
          { status: 'processing', message: 'Generating output...', progress: 70 },
          { status: 'processing', message: 'Finalizing results...', progress: 90 },
          { status: 'complete', message: 'Execution complete!', progress: 100 },
        ];

        for (const update of statuses) {
          await new Promise((resolve) => setTimeout(resolve, 1500));
          updateExecution(execution.id, {
            status: update.status,
            statusMessage: update.message,
            progress: update.progress,
          });

          if (update.status === 'complete') {
            // Add mock result
            updateExecution(execution.id, {
              completedAt: new Date(),
              result: {
                type: selectedAgent.outputType,
                summary: `## Execution Summary\n\nThe **${selectedAgent.name}** completed successfully.\n\n### Inputs Processed\n${Object.entries(data)
                  .map(([key, value]) => `- **${key}**: ${value}`)
                  .join('\n')}\n\n### Next Steps\nReview the generated output in the Content tab.`,
                content:
                  selectedAgent.outputType === 'code'
                    ? `// Generated by ${selectedAgent.name}\n// Execution ID: ${execution.id}\n\nfunction generatedCode() {\n  // Your generated code will appear here\n  console.log('Agent execution successful');\n}\n\nexport default generatedCode;`
                    : `# Generated Documentation\n\nThis is sample output from the **${selectedAgent.name}**.\n\n## Overview\n\nThe agent has processed your request and generated the following content.\n\n## Details\n\n- Input parameters were validated\n- Business logic was analyzed\n- Output was formatted according to standards\n\n## Recommendations\n\n1. Review the generated content\n2. Make necessary adjustments\n3. Deploy to your target environment`,
                files: [
                  {
                    name: `${selectedAgent.id}-output.${selectedAgent.outputType === 'code' ? 'ts' : 'md'}`,
                    type: selectedAgent.outputType === 'code' ? 'text/typescript' : 'text/markdown',
                  },
                ],
              },
            });
            setViewState('results');
          }
        }
      };

      simulateProgress();
    },
    [selectedAgent, setCurrentExecution, addExecution, setViewState, updateExecution]
  );

  const handleNewExecution = useCallback(() => {
    setViewState('form');
    setCurrentExecution(null);
  }, [setViewState, setCurrentExecution]);

  return (
    <div className="relative min-h-screen flex flex-col items-center justify-center overflow-hidden bg-gradient-animated">
      {/* Background effects */}
      <div className="absolute inset-0 overflow-hidden pointer-events-none">
        {/* Radial gradient overlay */}
        <div
          className="absolute inset-0"
          style={{
            background:
              'radial-gradient(circle at 50% 50%, rgba(0, 144, 181, 0.08) 0%, transparent 50%)',
          }}
        />

        {/* Grid pattern */}
        <div
          className="absolute inset-0 opacity-[0.02]"
          style={{
            backgroundImage: `
              linear-gradient(rgba(255,255,255,0.1) 1px, transparent 1px),
              linear-gradient(90deg, rgba(255,255,255,0.1) 1px, transparent 1px)
            `,
            backgroundSize: '50px 50px',
          }}
        />

        {/* Animated particles */}
        {[...Array(20)].map((_, i) => (
          <motion.div
            key={i}
            className="absolute w-1 h-1 rounded-full bg-primary/30"
            style={{
              left: `${Math.random() * 100}%`,
              top: `${Math.random() * 100}%`,
            }}
            animate={{
              y: [0, -30, 0],
              opacity: [0.2, 0.5, 0.2],
            }}
            transition={{
              duration: 3 + Math.random() * 2,
              repeat: Infinity,
              delay: Math.random() * 2,
            }}
          />
        ))}
      </div>

      {/* Header */}
      <motion.header
        className="absolute top-0 left-0 right-0 p-6 flex items-center justify-between z-10"
        initial={{ opacity: 0, y: -20 }}
        animate={{ opacity: 1, y: 0 }}
      >
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl bg-primary/20 border border-primary/40 flex items-center justify-center">
            <span className="text-primary font-bold text-lg">S</span>
          </div>
          <div>
            <h1 className="text-lg font-semibold text-foreground">SYSPRO AI Hub</h1>
            <p className="text-xs text-foreground-muted">Agent Orchestration Platform</p>
          </div>
        </div>

        <div className="flex items-center gap-4">
          <div className="flex items-center gap-2 px-3 py-1.5 rounded-lg bg-success/20 text-success text-sm">
            <span className="w-2 h-2 rounded-full bg-success animate-pulse" />
            System Online
          </div>
        </div>
      </motion.header>

      {/* Main content */}
      <main className="relative z-10 flex flex-col items-center justify-center flex-1 w-full px-6 py-24">
        <AnimatePresence mode="wait">
          {/* Orbit View */}
          {viewState === 'orbit' && (
            <motion.div
              key="orbit"
              className="flex flex-col items-center gap-8"
              initial={{ opacity: 0, scale: 0.9 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.9 }}
              transition={{ duration: 0.5 }}
            >
              <OrbitSystem
                agents={agents}
                onAgentSelect={handleAgentSelect}
                orbitRadius={200}
              />

              <motion.p
                className="text-foreground-secondary text-center max-w-md"
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ delay: 0.5 }}
              >
                Select an agent to begin, or describe what you need
              </motion.p>

              <CommandInput agents={agents} onAgentSelect={handleAgentSelect} />
            </motion.div>
          )}

          {/* Form View */}
          {viewState === 'form' && selectedAgent && (
            <motion.div
              key="form"
              className="w-full flex flex-col items-center"
              initial={{ opacity: 0, x: 50 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: -50 }}
              transition={{ duration: 0.3 }}
            >
              <DynamicForm
                agent={selectedAgent}
                onSubmit={handleFormSubmit}
                onBack={handleBack}
              />
            </motion.div>
          )}

          {/* Executing View */}
          {viewState === 'executing' && selectedAgent && currentExecution && (
            <motion.div
              key="executing"
              className="w-full flex flex-col items-center"
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.95 }}
              transition={{ duration: 0.3 }}
            >
              <ExecutionMonitor
                execution={currentExecution}
                agent={selectedAgent}
                onCancel={handleBack}
              />
            </motion.div>
          )}

          {/* Results View */}
          {viewState === 'results' && selectedAgent && currentExecution?.result && (
            <motion.div
              key="results"
              className="w-full flex flex-col items-center"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -20 }}
              transition={{ duration: 0.3 }}
            >
              <ResultsViewer
                result={currentExecution.result}
                agent={selectedAgent}
                onNewExecution={handleNewExecution}
                onBack={handleBack}
              />
            </motion.div>
          )}
        </AnimatePresence>
      </main>

      {/* Footer */}
      <motion.footer
        className="absolute bottom-0 left-0 right-0 p-6 flex items-center justify-center z-10"
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ delay: 0.5 }}
      >
        <p className="text-xs text-foreground-muted">
          Powered by Claude Code Agents & n8n Workflows
        </p>
      </motion.footer>
    </div>
  );
}
